### ISSUE TITLE
Unable to find plugin

### ISSUE THREAD

**Issue by loner001** [maxclaey/homebridge-piper#2]
Hello, 
I was trying to follow the procedure however got stuck at step 2 where it requires to install "homebridge-piper" plugin. I can't seem to find the plugin itself, can you please advise. Thanks in advance.

**Comment by maxclaey** [comment]
This plugin is not published through npm. You should download the plugin from github and install locally.

**Comment by loner001** [comment]
Hello,

This is my first time using this environment, would you mind explaining in more detail how to install the plugin locally. Thanks in advance and Merry Christmas.

**Comment by maxclaey** [comment]
When you downloaded the project (folder homebridge-piper), execute the following command in the location where the folder is stored (not inside the folder itself): npm install homebridge piper. When you want to install globally, use the flag -g
